package cn.st.spring.mybatis.mapper;

import cn.st.spring.mybatis.base.BaseMapper;
import cn.st.spring.mybatis.entity.GovUser;
import cn.st.spring.mybatis.entity.GovUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GovUserMapper extends BaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_user
     *
     * @mbg.generated
     */
    long countByExample(GovUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_user
     *
     * @mbg.generated
     */
    int deleteByExample(GovUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_user
     *
     * @mbg.generated
     */
    int insert(GovUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_user
     *
     * @mbg.generated
     */
    int insertSelective(GovUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_user
     *
     * @mbg.generated
     */
    List<GovUser> selectByExample(GovUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_user
     *
     * @mbg.generated
     */
    GovUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") GovUser record, @Param("example") GovUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") GovUser record, @Param("example") GovUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(GovUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gov_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GovUser record);
}