version: '2'
services:
  db:
    image: "mysql:5.7.18"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=dev
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev
    command: ['--character-set-server=utf8mb4','--collation-server=utf8mb4_unicode_ci']

  init:
    build: ./init
    volumes:
      - ./init/bin:/mnt/bin
      - ./init/sql:/mnt/sql
    depends_on:
      - db
